[2024-11-05T20:38:06.846+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T20:38:06.873+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_transaction_analysis2.create_telegram_message scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T20:38:06.887+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_transaction_analysis2.create_telegram_message scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T20:38:06.888+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-05T20:38:06.907+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_telegram_message> on 2024-11-04 00:00:00+00:00
[2024-11-05T20:38:06.915+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T20:38:06.916+0000] {standard_task_runner.py:72} INFO - Started process 88 to run task
[2024-11-05T20:38:06.917+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_transaction_analysis2', 'create_telegram_message', 'scheduled__2024-11-04T00:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/fraud_transaction_analysis2-dag.py', '--cfg-path', '/tmp/tmp_xdddb0n']
[2024-11-05T20:38:06.919+0000] {standard_task_runner.py:105} INFO - Job 108: Subtask create_telegram_message
[2024-11-05T20:38:06.986+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_transaction_analysis2.create_telegram_message scheduled__2024-11-04T00:00:00+00:00 [running]> on host 21d07c241839
[2024-11-05T20:38:07.124+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fraud_transaction_analysis2' AIRFLOW_CTX_TASK_ID='create_telegram_message' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T00:00:00+00:00'
[2024-11-05T20:38:07.126+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-05T20:38:07.126+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-05T20:38:07.127+0000] {logging_mixin.py:190} INFO - Current task name:create_telegram_message state:running start_date:2024-11-05 20:38:06.874381+00:00
[2024-11-05T20:38:07.128+0000] {logging_mixin.py:190} INFO - Dag name:fraud_transaction_analysis2 and current dag run status:running
[2024-11-05T20:38:07.129+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T20:38:07.130+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_transaction_analysis2-dag.py", line 29, in create_telegram_message
    f"Сумма в биткоинах: {total_amount_btc:.8f} BTC\n"
                         ^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'
[2024-11-05T20:38:07.150+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-05T20:38:07.152+0000] {logging_mixin.py:190} INFO - Task start:2024-11-05 20:38:06.874381+00:00 end:2024-11-05 20:38:07.150334+00:00 duration:0.275953
[2024-11-05T20:38:07.153+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): create_telegram_message> dag:<DAG: fraud_transaction_analysis2> dagrun:<DagRun fraud_transaction_analysis2 @ 2024-11-04 00:00:00+00:00: scheduled__2024-11-04T00:00:00+00:00, state:running, queued_at: 2024-11-05 20:37:54.224136+00:00. externally triggered: False>
[2024-11-05T20:38:07.154+0000] {logging_mixin.py:190} INFO - Failure caused by Unknown format code 'f' for object of type 'str'
[2024-11-05T20:38:07.155+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=fraud_transaction_analysis2, task_id=create_telegram_message, run_id=scheduled__2024-11-04T00:00:00+00:00, execution_date=20241104T000000, start_date=20241105T203806, end_date=20241105T203807
[2024-11-05T20:38:07.169+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T20:38:07.170+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 108 for task create_telegram_message (Unknown format code 'f' for object of type 'str'; 88)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_transaction_analysis2-dag.py", line 29, in create_telegram_message
    f"Сумма в биткоинах: {total_amount_btc:.8f} BTC\n"
                         ^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'
[2024-11-05T20:38:07.213+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T20:38:07.224+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-11-05T20:38:07.242+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T20:38:07.246+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
